# Generated by Django 4.2.4 on 2023-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_newtable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newtable',
            table='new_table',
        ),
    ]
